# vim: set syn=conf ft=conf:

include=~~home/local.conf
# default is too low
volume-max=500
# don't start gui for audio only
audio-display=no

[big]
video-reversal-buffer=256M
audio-reversal-buffer=16M
demuxer-readahead-secs=60
demuxer-max-bytes=1536M

# GUI for audio
[gaudio]
player-operation-mode=pseudo-gui

[audio-img]
audio-display=embedded-first

[revert-fast] # when fast is default
scale=lanczos
dscale=lanczos
dither=fruit
correct-downscaling=yes
linear-downscaling=yes
sigmoid-upscaling=yes
hdr-compute-peak=yes
allow-delayed-peak-detect=no
